import { Label } from "@mui/icons-material";

const dashboardData = [
  { id: 0, status: "New Applications", count: 6 },
  { id: 1, status: "Pending Applications", count: 12 },
  { id: 2, status: "In Progress Applications", count: 14 },
  { id: 3, status: "Rejected Applications", count: 4 },
  { id: 4, status: "Completed Applications", count: 105 },
];

export const loanData = [
  {
    id: 1,
    loanType: "Home Loan",
    status: "Pre-approved",
    applicantName: "VIJAYPRASAD MOTILAL PARAB",
    cibilScore: 742,
    amount: "20,50,000",
  },
  {
    id: 2,
    loanType: "Home Loan",
    status: "Pre-approved",
    applicantName: "VIJAYPRASAD MOTILAL PARAB",
    cibilScore: 742,
    amount: "20,50,000",
  },
  {
    id: 3,
    loanType: "Home Loan",
    status: "Pre-approved",
    applicantName: "VIJAYPRASAD MOTILAL PARAB",
    cibilScore: 742,
    amount: "20,50,000",
  },
  {
    id: 4,
    loanType: "Home Loan",
    status: "Pre-approved",
    applicantName: "VIJAYPRASAD MOTILAL PARAB",
    cibilScore: 742,
    amount: "20,50,000",
  },
];

export const subAgentData = [
  {
    id: 1,
    phone: "+91 90000 00000",
    userType: "Sub User",
    name: "SACHIN MANIKCHAND PARSHI",
    rank: 2,
    totalBusiness: "11,00,000",
  },
  {
    id: 2,
    phone: "+91 90001 00001",
    userType: "Sub User",
    name: "RAHUL SHARMA",
    rank: 1,
    totalBusiness: "15,00,000",
  },
  {
    id: 3,
    phone: "+91 90002 00002",
    userType: "Sub User",
    name: "AMIT KUMAR",
    rank: 3,
    totalBusiness: "9,50,000",
  },
  {
    id: 4,
    phone: "+91 90003 00003",
    userType: "Sub User",
    name: "SUNIL VERMA",
    rank: 4,
    totalBusiness: "8,00,000",
  },
];

export const userFormSections = [
  {
    title: "Personal Information",
    status: "Pending",
    content: "Fill in your personal details.",
  },
  {
    title: "Family Details",
    status: "Pending",
    content: "Provide your family information.",
  },
  {
    title: "Income Details",
    status: "Pending",
    content: "Share your income details.",
  },
];
export const userData = [
  {
    id: 1,
    applicantName: "Prathmesh MOTILAL PARAB",
    applications: 742,
    amount: "20,50,000",
  },
  {
    id: 2,
    applicantName: "VIJAYPRASAD MOTILAL PARAB",
    applications: 742,
    amount: "20,50,000",
  },
  {
    id: 3,
    applicantName: "VIJAYPRASAD MOTILAL PARAB",
    applications: 742,
    amount: "20,50,000",
  },
  {
    id: 4,
    applicantName: "VIJAYPRASAD MOTILAL PARAB",
    applications: 742,
    amount: "20,50,000",
  },
];
export const bankOperatorData = [
  {
    key: 1,
    bankOperatorType: "Public",
    isSetting: true,
    bankOperatorName: "State Bank of India",
    applications: 120,
    amount: 5000000,
  },
  {
    key: 2,
    bankOperatorType: "Private",
    bankOperatorName: "HDFC Bank",
    applications: 95,
    amount: 4200000,
  },
  {
    key: 3,
    bankOperatorType: "Public",
    bankOperatorName: "Punjab National Bank",
    applications: 80,
    amount: 3500000,
  },
  {
    key: 4,
    bankOperatorType: "Cooperative",
    bankOperatorName: "Saraswat Bank",
    applications: 60,
    amount: 2800000,
  },
  {
    key: 5,
    bankOperatorType: "Private",
    bankOperatorName: "ICICI Bank",
    applications: 110,
    amount: 4700000,
  },
];
export const allLoanTypes = [
  "Personal Loan",
  "Home Loan",
  "Car Loan",
  "Credit Card Loans",
  "Business Loan",
  "Loan Against Property",
  "2 Wheeler Loan",
  "Small Business Loan",
  "Cash Credit",
  "Loan Against Securities",
  "Salary Loan",
  "Project Loan",
  "Agriculture Loan",
  "Cash Advances",
  "Gold Loan",
  "Education Loan",
];
//'masterAdmin', 'admin', 'agent', 'subAgent', 'user', 'bankOperator'
export const sidebarList = {
  dashboard: {
    role: ["masterAdmin", "admin", "agent", "subAgent", "bankOperator"],
    route: "/",
    icon: "dashboard",
    name: "Dashboard",
    value: "dashboard",
  },
  applications: {
    role: ["masterAdmin", "admin", "agent", "bankOperator", "subAgent"],
    route: "/applications",
    icon: "applications",
    name: "Applications",
    value: "applications",
  },
  users: {
    role: ["masterAdmin", "admin", "agent"],
    route: "/users",
    icon: "users",
    name: "Users",
    value: "users",
  },
    clientList: {
    role: ["agent", "client"],
    route: "/client",
    icon: "clientList",
    name: "Client List",
    value: "clientList",
  },
  earning: {
    role: ["masterAdmin", "admin", "agent"],
    route: "/earning",
    icon: "earning",
    name: "Earning",
    value: "earning",
  },
  notifications: {
    role: ["masterAdmin", "admin", "agent", "bankOperator", "user", "subAgent"],
    route: "/acceptreject",
    icon: "notifications",
    name: "Notifications",
    value: "notifications",
  },
  lender: {
    role: ["masterAdmin", "admin", "bankOperator"],
    route: "/bank/lender",
    icon: "lender",
    name: "Lender",
    value: "lender",
  },
  bankOperator: {
    role: ["masterAdmin", "admin"],
    route: "/bank?type=bankOperator",
    icon: "bankOperator",
    name: "Bank List",
    value: "bankOperator",
  },
  profile: {
    role: ["masterAdmin", "admin", "agent", "subAgent", "user", "bankOperator"],
    route: "/profile",
    icon: "user",
    name: "Profile",
    value: "profile",
  },
  help: {
    role: ["masterAdmin", "admin", "agent", "subAgent", "bankOperator", "user"],
    route: "/help",
    icon: "help",
    name: "Help",
    value: "help",
  },
  setting: {
    role: ["masterAdmin", "admin"],
    route: "/setting",
    icon: "setting",
    name: "setting",
    value: "setting",
  },
  logout: {
    role: ["masterAdmin", "admin", "agent", "subAgent", "user", "bankOperator"],
    // route: "/logout",
    icon: "logout",
    name: "Logout",
    value: "logout",
  },
};
// 'Dashboard', 'Applications', 'User', 'Earning', 'Notifications', 'Lender', 'Bank List', 'Profile', 'Help', 'setting', 'Logout'

export const investments = [
  {
    key: "stocks",
    value: "Stocks",
    description: "Equity investments representing ownership in companies.",
  },
  {
    key: "bonds",
    value: "Bonds",
    description:
      "Fixed-income securities issued by governments or corporations.",
  },
  {
    key: "mutual_funds",
    value: "Mutual Funds",
    description:
      "Professionally managed investment funds pooling money from investors.",
  },
  {
    key: "fixed_deposits",
    value: "Fixed Deposits",
    description:
      "Bank deposits with fixed interest rates and maturity periods.",
  },
  {
    key: "real_estate",
    value: "Real Estate",
    description:
      "Investments in physical properties like land, houses, or commercial buildings.",
  },
  {
    key: "ppf",
    value: "Public Provident Fund (PPF)",
    description:
      "A long-term tax-saving investment with government-backed security.",
  },
  {
    key: "cryptocurrencies",
    value: "Cryptocurrencies",
    description:
      "Digital assets like Bitcoin, Ethereum, and other blockchain-based currencies.",
  },
  {
    key: "other",
    value: "Other",
    description: "Any other type of investment not listed here.",
  },
];
export const bankData = [
  { id: 1, name: "Bank 1", address: "Address 1" },
  { id: 2, name: "Bank 2", address: "Address 2" },
  { id: 3, name: "Bank 3", address: "Address 3" },
];

export const nationality = [
  "Afghanistan",
  "Albania",
  "Algeria",
  "Andorra",
  "Angola",
  "Antigua and Barbuda",
  "Argentina",
  "Armenia",
  "Australia",
  "Austria",
  "Azerbaijan",
  "Bahamas",
  "Bahrain",
  "Bangladesh",
  "Barbados",
  "Belarus",
  "Belgium",
  "Belize",
  "Benin",
  "Bhutan",
  "Bolivia",
  "Bosnia and Herzegovina",
  "Botswana",
  "Brazil",
  "Brunei",
  "Bulgaria",
  "Burkina Faso",
  "Burundi",
  "Cabo Verde",
  "Cambodia",
  "Cameroon",
  "Canada",
  "Central African Republic",
  "Chad",
  "Chile",
  "China",
  "Colombia",
  "Comoros",
  "Congo, Democratic Republic of the",
  "Congo, Republic of the",
  "Costa Rica",
  "Croatia",
  "Cuba",
  "Cyprus",
  "Czech Republic",
  "Denmark",
  "Djibouti",
  "Dominica",
  "Dominican Republic",
  "Ecuador",
  "Egypt",
  "El Salvador",
  "Equatorial Guinea",
  "Eritrea",
  "Estonia",
  "Eswatini",
  "Ethiopia",
  "Fiji",
  "Finland",
  "France",
  "Gabon",
  "Gambia",
  "Georgia",
  "Germany",
  "Ghana",
  "Greece",
  "Grenada",
  "Guatemala",
  "Guinea",
  "Guinea-Bissau",
  "Guyana",
  "Haiti",
  "Honduras",
  "Hungary",
  "Iceland",
  "India",
  "Indonesia",
  "Iran",
  "Iraq",
  "Ireland",
  "Israel",
  "Italy",
  "Ivory Coast",
  "Jamaica",
  "Japan",
  "Jordan",
  "Kazakhstan",
  "Kenya",
  "Kiribati",
  "Korea, North",
  "Korea, South",
  "Kosovo",
  "Kuwait",
  "Kyrgyzstan",
  "Laos",
  "Latvia",
  "Lebanon",
  "Lesotho",
  "Liberia",
  "Libya",
  "Liechtenstein",
  "Lithuania",
  "Luxembourg",
  "Madagascar",
  "Malawi",
  "Malaysia",
  "Maldives",
  "Mali",
  "Malta",
  "Marshall Islands",
  "Mauritania",
  "Mauritius",
  "Mexico",
  "Micronesia",
  "Moldova",
  "Monaco",
  "Mongolia",
  "Montenegro",
  "Morocco",
  "Mozambique",
  "Myanmar",
  "Namibia",
  "Nauru",
  "Nepal",
  "Netherlands",
  "New Zealand",
  "Nicaragua",
  "Niger",
  "Nigeria",
  "North Macedonia",
  "Norway",
  "Oman",
  "Pakistan",
  "Palau",
  "Palestine",
  "Panama",
  "Papua New Guinea",
  "Paraguay",
  "Peru",
  "Philippines",
  "Poland",
  "Portugal",
  "Qatar",
  "Romania",
  "Russia",
  "Rwanda",
  "Saint Kitts and Nevis",
  "Saint Lucia",
  "Saint Vincent and the Grenadines",
  "Samoa",
  "San Marino",
  "Sao Tome and Principe",
  "Saudi Arabia",
  "Senegal",
  "Serbia",
  "Seychelles",
  "Sierra Leone",
  "Singapore",
  "Slovakia",
  "Slovenia",
  "Solomon Islands",
  "Somalia",
  "South Africa",
  "South Sudan",
  "Spain",
  "Sri Lanka",
  "Sudan",
  "Suriname",
  "Sweden",
  "Switzerland",
  "Syria",
  "Taiwan",
  "Tajikistan",
  "Tanzania",
  "Thailand",
  "Timor-Leste",
  "Togo",
  "Tonga",
  "Trinidad and Tobago",
  "Tunisia",
  "Turkey",
  "Turkmenistan",
  "Tuvalu",
  "Uganda",
  "Ukraine",
  "United Arab Emirates",
  "United Kingdom",
  "United States",
  "Uruguay",
  "Uzbekistan",
  "Vanuatu",
  "Vatican City",
  "Venezuela",
  "Vietnam",
  "Yemen",
  "Zambia",
  "Zimbabwe",
];

// create the range and a a standard one value of that range from 0 to 100 by 10 gap
export const percentageRange=["0% to 10%","11% to 20%","21% to 30%","31% to 40%","41% to 50%","51% to 60%","61% to 70%","71% to 80%","81% to 90%","91% to 100%"]

export default dashboardData;
